modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/jj21asd/BetterSmithingUI/issues"
license = "MIT"

[[mods]]
modId = "better_smithing_ui"
version = "${version}"
displayName = "Better Smithing UI"
authors = "jj21"
description = '''Replaces the ugly vanilla smithing menu with an improved version.'''
logoFile = "icon.png"

[[dependencies.better_smithing_ui]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.6,)"
ordering = "AFTER"
side = "BOTH"
