modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/jj21asd/BetterSmithingUI/issues"
license = "MIT"

[[mods]]
modId = "better_smithing_ui"
version = "${version}"
displayName = "Better Smithing UI"
authors = "jj21"
description = '''Replaces the ugly vanilla smithing menu with an improved version'''
logoFile = "icon.png"

[[dependencies.better_smithing_ui]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.better_smithing_ui]]
modId = "architectury"
type = "required"
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "better_smithing_ui.mixins.json"
